# Book settings. Learn more at https://jupyterbook.org/customize/config.html
title                       : Uncertainty and Sensitivity Analysis of Model Output in Engineering Applications
author                      : Adem R.N. Aouichaoui and Gürkan Sin
copyright                   : "2023"
logo                        : logo.png       # logo in top-left corner
only_build_toc_files        : true           # whether to ignore the extra files
exclude_patterns            : ["README.md", "LICENSE.md", "**_master.ipynb"]

########################################################################
# Force re-execution of notebooks on each build. See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache      #cache # auto # force
  timeout          : 5000       # max seconds for notebook to execute

########################################################################
# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: uncert_dtu.tex

########################################################################
# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
